version: '3.7'

services:
  nacos:
    container_name: nacos_1
    image: nacos/nacos-server
    restart: always
    environment:
      MODE: standalone
      PREFER_HOST_MODE: host
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: db
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: 123456
      MYSQL_SERVICE_DB_PARAM: characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&serverTimezone=GMT+8
      MYSQL_DATABASE_NUM: 1
    ports:
      - "8848:8848"
    networks:
      my_network:

