version: '3.7'

services:
  db:
    container_name: mysql_1
    image: mysql:5.7
    hostname: mysql
    volumes:
      - /root/wordpress/db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    networks:
      my_network:
  wordpress:
    container_name: wordpress_1
    image: wordpress
    hostname: wordpress
    restart: always
    depends_on:
      - db
    links:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 123456
      WORDPRESS_DB_NAME: wordpress
    ports:
      - "80:80"
    volumes:
      - /root/wordpress/wordpress_data:/var/www/html
    networks:
      my_network:

networks:
  my_network:
    name: my_network


